import { describe, it, expect } from "vitest";
import {
  parseRequirementsTxt,
  parsePoetryLockfile,
} from "../../src/lockfiles/python.js";

describe("parseRequirementsTxt", () => {
  it("parses pinned entries and lowercases names", () => {
    const text = `Django==4.2.5\nrequests==2.31.0\n`;
    expect(parseRequirementsTxt(text)).toEqual({
      packages: [
        { ecosystem: "PyPI", name: "django", version: "4.2.5" },
        { ecosystem: "PyPI", name: "requests", version: "2.31.0" },
      ],
      skipped: 0,
    });
  });

  it("strips environment markers and hash options", () => {
    const text = `numpy==1.26.0 ; python_version >= "3.9"\nflask==3.0.0 --hash=sha256:abc\n`;
    expect(parseRequirementsTxt(text).packages).toEqual([
      { ecosystem: "PyPI", name: "numpy", version: "1.26.0" },
      { ecosystem: "PyPI", name: "flask", version: "3.0.0" },
    ]);
  });

  it("strips extras like pkg[ext]==1.0", () => {
    const text = `requests[security]==2.31.0\n`;
    expect(parseRequirementsTxt(text).packages).toEqual([
      { ecosystem: "PyPI", name: "requests", version: "2.31.0" },
    ]);
  });

  it("skips comments, blank lines, and pip directives", () => {
    const text = `# top comment\n\n-r dev.txt\n--index-url=https://example.com\n-e .\nfoo==1.0.0\n`;
    const r = parseRequirementsTxt(text);
    expect(r.packages).toEqual([
      { ecosystem: "PyPI", name: "foo", version: "1.0.0" },
    ]);
    // -r/--index-url/-e all start with `-` so silent-skip; URLs/paths count as skipped.
    expect(r.skipped).toBe(0);
  });

  it("counts URLs and local paths as skipped", () => {
    const text = `git+https://github.com/x/y.git\n./local-wheel.whl\nfoo==1.0\n`;
    const r = parseRequirementsTxt(text);
    expect(r.packages).toHaveLength(1);
    expect(r.skipped).toBe(2);
  });

  it("counts unpinned (>=, ~=) entries as skipped", () => {
    const text = `looselib>=1.0\ntilde~=2.0\npinned==3.0\n`;
    const r = parseRequirementsTxt(text);
    expect(r.packages).toEqual([
      { ecosystem: "PyPI", name: "pinned", version: "3.0" },
    ]);
    expect(r.skipped).toBe(2);
  });

  it("dedupes duplicate (name, version) entries", () => {
    const text = `requests==2.31.0\nrequests==2.31.0\n`;
    expect(parseRequirementsTxt(text).packages).toHaveLength(1);
  });
});

describe("parsePoetryLockfile", () => {
  it("parses [[package]] blocks", () => {
    const text = `# autogenerated
[[package]]
name = "requests"
version = "2.31.0"
description = "HTTP for humans"

[[package]]
name = "urllib3"
version = "2.0.7"
`;
    expect(parsePoetryLockfile(text)).toEqual([
      { ecosystem: "PyPI", name: "requests", version: "2.31.0" },
      { ecosystem: "PyPI", name: "urllib3", version: "2.0.7" },
    ]);
  });

  it("lowercases names (PyPI names are case-insensitive)", () => {
    const text = `[[package]]\nname = "Django"\nversion = "4.2.5"\n`;
    expect(parsePoetryLockfile(text)).toEqual([
      { ecosystem: "PyPI", name: "django", version: "4.2.5" },
    ]);
  });

  it("includes dev-category packages", () => {
    const text = `[[package]]
name = "pytest"
version = "8.0.0"
category = "dev"
`;
    expect(parsePoetryLockfile(text)).toEqual([
      { ecosystem: "PyPI", name: "pytest", version: "8.0.0" },
    ]);
  });

  it("ignores non-package sections like [metadata]", () => {
    const text = `[[package]]
name = "foo"
version = "1.0.0"

[metadata]
lock-version = "2.0"
python-versions = "^3.10"
`;
    expect(parsePoetryLockfile(text)).toEqual([
      { ecosystem: "PyPI", name: "foo", version: "1.0.0" },
    ]);
  });

  it("handles attribute order: version before name", () => {
    const text = `[[package]]\nversion = "1.0.0"\nname = "foo"\n`;
    expect(parsePoetryLockfile(text)).toEqual([
      { ecosystem: "PyPI", name: "foo", version: "1.0.0" },
    ]);
  });
});
