import { describe, it, expect } from "vitest";
import {
  parseYarnV1Lockfile,
  parseYarnBerryLockfile,
  detectYarnVariant,
} from "../../src/lockfiles/yarn.js";

describe("parseYarnV1Lockfile", () => {
  it("parses a simple single-range entry", () => {
    const text = `# THIS IS AN AUTOGENERATED FILE
lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-...
`;
    expect(parseYarnV1Lockfile(text)).toEqual([
      { ecosystem: "npm", name: "lodash", version: "4.17.21" },
    ]);
  });

  it("dedupes a comma-list of ranges to one entry per (name, version)", () => {
    const text = `"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4":
  version "7.22.13"
  resolved "..."
`;
    const out = parseYarnV1Lockfile(text);
    expect(out).toEqual([
      { ecosystem: "npm", name: "@babel/code-frame", version: "7.22.13" },
    ]);
  });

  it("handles scoped packages", () => {
    const text = `"@types/node@^18.0.0":
  version "18.19.4"
`;
    expect(parseYarnV1Lockfile(text)).toEqual([
      { ecosystem: "npm", name: "@types/node", version: "18.19.4" },
    ]);
  });

  it("dedupes across multiple entries that resolve to the same version", () => {
    const text = `foo@^1.0.0:
  version "1.5.0"

foo@^1.2.0:
  version "1.5.0"
`;
    expect(parseYarnV1Lockfile(text)).toEqual([
      { ecosystem: "npm", name: "foo", version: "1.5.0" },
    ]);
  });

  it("throws clearly on a Berry-format file", () => {
    const text = `__metadata:\n  version: 6\n`;
    expect(() => parseYarnV1Lockfile(text)).toThrow(/Yarn Berry/);
  });
});

describe("parseYarnBerryLockfile", () => {
  it("parses a Berry lockfile with npm-protocol descriptors", () => {
    const text = `__metadata:
  version: 6
  cacheKey: 8

"lodash@npm:^4.17.0":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: ...
`;
    expect(parseYarnBerryLockfile(text)).toEqual([
      { ecosystem: "npm", name: "lodash", version: "4.17.21" },
    ]);
  });

  it("skips workspace: and patch: descriptors", () => {
    const text = `__metadata:
  version: 6

"my-app@workspace:.":
  version: 0.0.0-use.local
  resolution: "my-app@workspace:."

"react@npm:^18.0.0":
  version: 18.2.0
  resolution: "react@npm:18.2.0"

"lodash@patch:lodash@npm%3A4.17.20#./patches/lodash.patch":
  version: 4.17.20
  resolution: "lodash@patch:lodash@npm%3A4.17.20"
`;
    const out = parseYarnBerryLockfile(text);
    expect(out).toEqual([
      { ecosystem: "npm", name: "react", version: "18.2.0" },
    ]);
  });

  it("splits a comma-list descriptor into one entry", () => {
    const text = `__metadata:
  version: 6

"foo@npm:^1.0.0, foo@npm:^1.2.0":
  version: 1.5.0
  resolution: "foo@npm:1.5.0"
`;
    expect(parseYarnBerryLockfile(text)).toEqual([
      { ecosystem: "npm", name: "foo", version: "1.5.0" },
    ]);
  });

  it("throws clearly when handed a v1 file", () => {
    const text = `lodash@^4.17.0:\n  version "4.17.21"\n`;
    expect(() => parseYarnBerryLockfile(text)).toThrow(/Berry/);
  });
});

describe("detectYarnVariant", () => {
  it("recognises Berry by __metadata marker", () => {
    expect(detectYarnVariant("__metadata:\n  version: 6\n")).toBe("yarn-berry");
  });
  it("falls back to v1 otherwise", () => {
    expect(detectYarnVariant("# auto-generated\nfoo@^1:\n  version \"1.0.0\"")).toBe(
      "yarn",
    );
  });
});
