import { parse as parseYaml } from "yaml";
import type { Pkg } from "./types.js";

/**
 * Parse a Yarn v1 yarn.lock file.
 *
 * Yarn v1 has a custom non-YAML "yarn lockfile" format — it looks
 * YAML-ish but uses unquoted keys with quoting only for special chars,
 * and the entry header is a comma-separated list of name@range tuples.
 *
 * Format:
 *
 *     "@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4":
 *       version "7.22.13"
 *       resolved "..."
 *       integrity sha512-...
 *
 * We only need (name, resolved version), so a small regex pass is
 * dramatically simpler — and safer — than depending on Yarn's parser.
 */
export function parseYarnV1Lockfile(text: string): Pkg[] {
  // Bail clearly if someone hands us a Berry-format file.
  if (text.includes("__metadata:") || text.startsWith("# This file is generated by running")) {
    if (text.includes("__metadata:")) {
      throw new Error(
        "this is a Yarn Berry (v2+) lockfile, not v1 — call parseYarnBerryLockfile",
      );
    }
  }

  const lines = text.split(/\r?\n/);
  const out: Pkg[] = [];
  const seen = new Set<string>();
  let currentNames: string[] | null = null;

  for (const line of lines) {
    // Comments and blank lines reset nothing (entries are separated by
    // a blank line in v1, but a comment alone doesn't end an entry).
    if (line.startsWith("#")) continue;

    // Entry header: starts at column 0 and ends with ":" (after stripping
    // an optional trailing comment).
    if (line.length > 0 && !line.startsWith(" ") && line.endsWith(":")) {
      const header = line.slice(0, -1);
      // Split the comma list, strip quotes, then peel the @range off
      // each tuple. We only keep the package name — the same package
      // can appear under multiple ranges in one entry but resolves to
      // a single version.
      currentNames = header.split(",").map((part) => {
        const p = part.trim().replace(/^"|"$/g, "");
        // Last @ splits name from range — scoped names start with @.
        const at = p.lastIndexOf("@");
        return at > 0 ? p.slice(0, at) : p;
      });
      continue;
    }

    if (currentNames && line.trimStart().startsWith("version ")) {
      const m = line.trim().match(/^version\s+"?([^"\s]+)"?/);
      if (m && m[1]) {
        for (const name of currentNames) {
          const key = `${name}@${m[1]}`;
          if (!seen.has(key)) {
            seen.add(key);
            out.push({ ecosystem: "npm", name, version: m[1] });
          }
        }
      }
      currentNames = null;
    }
  }

  return out;
}

/**
 * Parse a Yarn Berry (v2+) yarn.lock file.
 *
 * Unlike v1 this is real YAML. The shape is:
 *
 *     "@babel/code-frame@npm:^7.0.0":
 *       version: 7.22.13
 *       resolution: "@babel/code-frame@npm:7.22.13"
 *       ...
 *
 * We parse the YAML, walk top-level keys, and split on `@npm:` to get
 * back the package name. Workspace-local entries (`@workspace:` or
 * `@patch:`) are skipped — those aren't real registry packages.
 */
export function parseYarnBerryLockfile(text: string): Pkg[] {
  // __metadata is the marker Berry writes; bail clearly otherwise.
  if (!text.includes("__metadata:")) {
    throw new Error("this does not look like a Yarn Berry lockfile (no __metadata block)");
  }

  const doc = parseYaml(text) as Record<string, { version?: string; resolution?: string }> | null;
  if (!doc) return [];

  const out: Pkg[] = [];
  const seen = new Set<string>();

  for (const [rawKey, entry] of Object.entries(doc)) {
    if (rawKey === "__metadata") continue;
    if (!entry || typeof entry !== "object") continue;
    const version = entry.version;
    if (!version) continue;

    // A key can be a comma-list of descriptors; for each, extract the
    // npm-protocol descriptors only.
    for (const descriptor of rawKey.split(",").map((s) => s.trim())) {
      // npm: protocol marks registry packages. Skip workspace:, patch:,
      // file:, git:, link:, portal: — none of those map to a CVE-able
      // published version.
      const npmIdx = descriptor.indexOf("@npm:");
      if (npmIdx < 0) continue;
      const name = descriptor.slice(0, npmIdx);
      if (!name) continue;
      const key = `${name}@${version}`;
      if (seen.has(key)) continue;
      seen.add(key);
      out.push({ ecosystem: "npm", name, version });
    }
  }

  return out;
}

/**
 * Distinguish Yarn v1 vs Berry from file contents. Used by the
 * loader so a single `yarn.lock` filename routes to the right parser.
 */
export function detectYarnVariant(text: string): "yarn" | "yarn-berry" {
  return text.includes("__metadata:") ? "yarn-berry" : "yarn";
}
