import { describe, it, expect } from "vitest";
import { debianComparator } from "../debian";

const cmp = debianComparator.cmp;

/**
 * Test fixtures grounded in `dpkg --compare-versions` ground truth.
 * Generated by running pairs through dpkg on a Debian 12 machine:
 *   dpkg --compare-versions "$A" lt "$B"  → exit 0 → A < B
 * Each test expresses one of: A < B, A == B, A > B.
 *
 * Covers: epoch handling, ~ prefix, upstream/revision split, leading
 * zeros in digit runs, letters vs symbols, real package versions.
 */

describe("debianComparator — basic equality", () => {
  it("identical strings", () => {
    expect(cmp("1.2.3", "1.2.3")).toBe(0);
  });
  it("epoch 0 absent vs epoch 0 explicit", () => {
    // Both parse to epoch=0, upstream=1.0, no revision → equal
    expect(cmp("1.0", "0:1.0")).toBe(0);
  });
});

describe("debianComparator — epoch", () => {
  it("epoch wins over upstream", () => {
    expect(cmp("1:1.0", "2.0")).toBeGreaterThan(0);
  });
  it("higher epoch always greater", () => {
    expect(cmp("2:0.1", "1:99.99")).toBeGreaterThan(0);
  });
  it("equal epoch defers to upstream", () => {
    expect(cmp("1:1.0", "1:2.0")).toBeLessThan(0);
  });
});

describe("debianComparator — tilde", () => {
  it("~rc1 < (no qualifier)", () => {
    expect(cmp("1.0~rc1", "1.0")).toBeLessThan(0);
  });
  it("~ < empty (end of string)", () => {
    expect(cmp("1.0~", "1.0")).toBeLessThan(0);
  });
  it("multiple tilde stages: ~alpha < ~beta < release", () => {
    expect(cmp("1.0~alpha", "1.0~beta")).toBeLessThan(0);
    expect(cmp("1.0~beta", "1.0")).toBeLessThan(0);
  });
});

describe("debianComparator — upstream version", () => {
  it("major higher wins", () => {
    expect(cmp("2.0", "1.99")).toBeGreaterThan(0);
  });
  it("digit run compared as integer (no lex 10 < 9)", () => {
    expect(cmp("1.10", "1.9")).toBeGreaterThan(0);
  });
  it("leading zeros ignored in digit runs", () => {
    expect(cmp("1.01", "1.1")).toBe(0);
  });
  it("letter section: a < b", () => {
    expect(cmp("1.0a", "1.0b")).toBeLessThan(0);
  });
  it("letters sort below symbols (+/./other)", () => {
    expect(cmp("1.0a", "1.0+")).toBeLessThan(0);
  });
  it("shorter string wins when prefix equal (no tilde)", () => {
    expect(cmp("1.0", "1.0.0")).toBeLessThan(0);
  });
});

describe("debianComparator — revision", () => {
  it("revision compared lex within same upstream", () => {
    expect(cmp("1.0-1", "1.0-2")).toBeLessThan(0);
  });
  it("having a revision > no revision", () => {
    expect(cmp("1.0", "1.0-1")).toBeLessThan(0);
  });
  it("revision-only difference: deb suffix sort", () => {
    expect(cmp("1.0-1+deb11u3", "1.0-1+deb11u4")).toBeLessThan(0);
  });
});

describe("debianComparator — real package versions", () => {
  it("openssl: 1.1.1n-0+deb11u3 < 1.1.1n-0+deb11u4", () => {
    expect(cmp("1.1.1n-0+deb11u3", "1.1.1n-0+deb11u4")).toBeLessThan(0);
  });
  it("openssl: 1.1.1n-0+deb11u3 < 3.0.0-1", () => {
    expect(cmp("1.1.1n-0+deb11u3", "3.0.0-1")).toBeLessThan(0);
  });
  it("chromium: 120.0.6099.71-1 > 119.0.6045.105-1", () => {
    expect(cmp("120.0.6099.71-1", "119.0.6045.105-1")).toBeGreaterThan(0);
  });
  it("kernel: 5.10.197-1 < 5.10.205-2", () => {
    expect(cmp("5.10.197-1", "5.10.205-2")).toBeLessThan(0);
  });
  it("apache: 2.4.57-2 > 2.4.54-1~deb11u1", () => {
    expect(cmp("2.4.57-2", "2.4.54-1~deb11u1")).toBeGreaterThan(0);
  });
  it("nodejs: 18.19.0~dfsg-6 < 18.19.0-deb12u1", () => {
    // ~dfsg sorts before release, so 18.19.0~dfsg < 18.19.0
    expect(cmp("18.19.0~dfsg-6", "18.19.0-deb12u1")).toBeLessThan(0);
  });
});

describe("debianComparator — edge cases", () => {
  it("0 placeholder is smallest", () => {
    expect(cmp("0", "0.0.0")).toBeLessThan(0);
  });
  it("transitive consistency: a < b < c implies a < c", () => {
    const a = "1.0~rc1";
    const b = "1.0";
    const c = "1.0-1";
    expect(cmp(a, b)).toBeLessThan(0);
    expect(cmp(b, c)).toBeLessThan(0);
    expect(cmp(a, c)).toBeLessThan(0);
  });
  it("antisymmetric: cmp(a, b) === -cmp(b, a)", () => {
    const pairs: [string, string][] = [
      ["1.0", "1.1"],
      ["1.0~rc1", "1.0"],
      ["1:1.0", "2.0"],
      ["1.0-1+deb11u3", "1.0-1+deb11u4"],
    ];
    for (const [x, y] of pairs) {
      const f = cmp(x, y);
      const r = cmp(y, x);
      expect(Math.sign(f)).toBe(-Math.sign(r));
    }
  });
});
